spring.application.name=residuos_back
# URL de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/Datos_Recomendaciones

# Usuario de la BD
spring.datasource.username=root

# Contraseña
spring.datasource.password=1234

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
